package com.param.designpattern.abstractfactory;

public class StripeInvoiceGenerator implements InvoiceGenerator{
    @Override
    public void generateInvoice(String orderId) {
        System.out.println("Invoce generated by Stripe for Orderid "+orderId);
    }
}
